net: rockchip_wlan: rtl8822cs: include puncturing bitmap in channel switch events
According to commit b345f06: ("wifi: cfg80211: include puncturing bitmap in channel
switch events")

This fixes following compilation error:
../drivers/net/wireless/rockchip_wlan/rtl8822cs/os_dep/linux/ioctl_cfg80211.c:518:52: error: too few arguments to function call, expected 3, have 2
  518 |         cfg80211_ch_switch_notify(adapter->pnetdev, &chdef);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~                         ^
../include/net/cfg80211.h:8276:6: note: 'cfg80211_ch_switch_notify' declared here
 8276 | void cfg80211_ch_switch_notify(struct net_device *dev,
      |      ^                         ~~~~~~~~~~~~~~~~~~~~~~~
 8277 |                                struct cfg80211_chan_def *chandef,
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 8278 |                                unsigned int link_id);
      |                                ~~~~~~~~~~~~~~~~~~~~

Change-Id: I9db821fc7b70ab7c2893c56ca9f8463342fe6da9
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>